### ISSUE TITLE
find, implement & document auth solution for hf & wandb 

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#121]
maybe we just don't pass tokens around and assume the user has them in env_variables / home dir? in this case we probably want to default to hf=True, wandb=True so it fails loudly if not provided, and has to be explicitly turned off

**Comment by SrGonao** [comment]
I agree

**Comment by jettjaniak** [comment]
HF fails loudly, TODO wandb

**Comment by jettjaniak** [comment]
actually, we should try to make a HF repo first and if it fails don't proceed with the training
