### ISSUE TITLE
rename models and tokenized dataset

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#14]
models should be just delphi-suite/{llama2,mamba}-#params
current models should have -v0 suffix
the same for current tokenized dataset

**Comment by jaidhyani** [comment]
Is this renaming the models and dataset in huggingface?

**Comment by jettjaniak** [comment]
yes

**Comment by jaidhyani** [comment]
Is it cool if I ask to join the delphi huggingface org?

**Comment by jettjaniak** [comment]
Yes, go ahead.

**Comment by jaidhyani** [comment]
Request sent (jaiwithani)

**Comment by jettjaniak** [comment]
accepted

**Comment by jettjaniak** [comment]
done, but with v0- prefix instead of suffix
