### ISSUE TITLE
figure out new model sizes

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#19]
names should include embed parameters
we want smaller than non-embed 100k

**Comment by SrGonao** [comment]
![image](https://github.com/delphi-suite/delphi/assets/30472805/28081539-898a-4141-bdb0-2a7caca2e542)

This is my proposal for mambas. Waiting on @jannik-brinkmann

**Comment by jannik-brinkmann** [comment]
<img width="846" alt="Screenshot 2024-03-18 at 22 54 20" src="https://github.com/delphi-suite/delphi/assets/62884101/e5f08625-9306-4a67-8551-afdeba1df5bf">

@jettjaniak
