### ISSUE TITLE
token map in HF

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#33]
@jaidhyani has more context

**Comment by jaidhyani** [comment]
It would be nice to have the token-position in huggingface (instead of as a pickle), as best practice if nothing else. Pickles are generally unsafe (they can execute arbitrary code on load), and we don't want to ask people to trust a potentially unsafe pickle to use our stuff.

**Comment by jettjaniak** [comment]
I expect 4096 rows under validation split
each row is either a list of tuples of (prompt_idx, pos_idx) or
each row has two features: prompt_idx and pos_idx
so hf_dataset[i]["prompt_idx"] and hf_dataset[i]["pos_idx"] are both lists of integers of the same length
