### ISSUE TITLE
manual token labeling

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#34]
@jaidhyani has more context

**Comment by jaidhyani** [comment]
It would be nice to have token labels (as in part of speech, etc) in a human-readable-and-writable format. This might look like a CSV with a row for each token and a column for each label, with cell values 1 or 0 if a label did or did not apply to that token. It would be relatively straightforward to read and write this CSV using sheets or excel, lowering the overhead of inspecting, revising, and adding to token labels.

**Comment by jettjaniak** [comment]
let's make CSV export, CSV import and make a google sheet with filters

**Comment by joshuawe** [comment]
So, just to be clear. 
This is just a different representation of the pickle file that we have already, correct?
Right now we have it in the non-ideal-inhumane-for of a dict with `token_id` and `token_label` pairs, where `token_label` is a dict again.
I have already converted it into a pandas table before (to create the visualizations of the label distribution over our tokens) and hence, could integrate it into the script that already creates the pickle file.

Do we maybe want to replace the pickle file?
Or do we want both files instead?

If this is what we're looking for, please assign this issue to me.
