### ISSUE TITLE
static assets in python package

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#36]
@jaidhyani has more context

**Comment by jaidhyani** [comment]
See: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data

Given dir structure:
```
project_root_directory
├── setup.py        # and/or setup.cfg, pyproject.toml
└── src
    └── mypkg
        ├── __init__.py
        ├── data1.rst
        ├── data2.rst
        ├── data1.txt
        └── data2.txt
```

You can add a `package_data` arg to `setup.py`:

```python3
from setuptools import setup, find_packages
setup(
    # ...,
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    package_data={"mypkg": ["*.txt", "*.rst"]}
)
```

And then access the static assets at runtime:
```python3
from importlib.resources import files
data_text = files('mypkg').joinpath('data1.txt').read_text()
```

**Comment by jaidhyani** [comment]
We want all static assets we're generating and want to be part of the project - pickles, csvs, whatever - to go to a standard data dir. How about `src/delphi/static/`?

**Comment by jettjaniak** [comment]
also move the files that are elsewhere now and paths in scripts that produce files
