### ISSUE TITLE
Inconsistencies in token labels

### ISSUE THREAD

**Issue by joshuawe** [delphi-suite/delphi#37]
Currently we have a distribution of labels as such:

![image](https://github.com/delphi-suite/delphi/assets/80349780/43f29240-6738-4cbc-af55-2d4c04b4ce70)

The tokenizer has a vocab of 4000 tokens, multiple classes/categories per token are possible.

However, the high number of nouns is suspicious. 
Many tokens are only partial words / word fragments, are they perhaps labelled as nouns?
Some tokens are words but they have  a "base" form. Is the actual token or the base form used by spaCy to create the token labels?

Do the following:
- [ ] Manually screen through more labels, how often does a label seem to fit or not fit
- [ ] How are word fragments labelled? -> Is there an easy way to find a "full word" category?
- [ ] Sanity check: are all our tokens also comprised in the vocabulary of the spaCy model?

**Comment by jettjaniak** [comment]
I consider #34 a pre-requisite

**Comment by joshuawe** [comment]
### How to get `is_word` category labels

- Downloaded the ~230k word list from nltk (nlp library)
- sanitized it by removing non-words of length 1 and 2
- Results show that many words such as 'played' or 'started' were not in the big 230k word list. 

### Alternative 1
Do the labelling manually. 
2 people do the entire list of 4096 tokens and manually label word or not word.
Expected time per person: 3- 4 hours per person
Downside: non-native speakers will make mistakes

### Alternative 2
Use Merriam Webster API: https://dictionaryapi.com/products/api-collegiate-dictionary
Good part: Free access to their base of 225,000 entries. Code is kind of ready.
Downside: Only 1000 API request per day per API key.
<details>
<summary>Code:</summary>

```Python 
import requests

def is_whole_word_merriam_webster(token, api_key):
    url = f"https://dictionaryapi.com/api/v3/references/collegiate/json/{token}?key={api_key}"
    response = requests.get(url)
    if response.status_code == 200:
        # If the response contains a list with entries, it's likely a word
        return len(response.json()) > 0 and isinstance(response.json()[0], dict)
    return False

# Example usage
api_key = 'YOUR_API_KEY'
tokens = ['example', 'txt', 'Python', 'nlp']
results = {token: is_whole_word_merriam_webster(token, api_key) for token in tokens}

for token, is_word in results.items():
    print(f"{token}: {'is a word' if is_word else 'is not a word'}")

```
</details>

Will go for Option 2, but have more important things to do currently.
