### ISSUE TITLE
Static dir follow-ups

### ISSUE THREAD

**Issue by jaidhyani** [delphi-suite/delphi#42]
Minor follow-up tasks for scripts writing to the static output dir #41 (`label_all_tokens.py`) 

1. We shouldn't necessarily force the output into the `STATIC_ASSETS_DIR`. Especially if the user specified a full path or a partial path with directory references, e.g.:
 
 `/home/me/Desktop/tokens.csv`
 `subdir/tokens.csv`
 
In the first case, the user has specified a full path, and we should use it. In the second, we can assume they're referring to a relative path from the current working directory, and we should output there.
 
We can get that behavior by calling `os.path.split` on the path arg, which returns a (head,tail) tuple. If `head` is empty, the user just passed a filename and we can probably throw it in the default output dir. If head isn't empty, we can call `os.path.expandvars` on the path arg to get the path we should output to.
 
2. We should also print the full path before writing, just to be explicit with the user about what file is being created and they know exactly where to look for it when it's done.

3. We should print out something when the export has completed successfully.

**Comment by menamerai** [comment]
I'll get this done, ideally before Friday or during the weekend after the previous issue #41 is resolved and merged.

**Comment by menamerai** [comment]
@jaidhyani I think currently this issue won't have much of an impact on our library, since the token mapping will be uploaded to HF and not be locally saved, and Joshua already took care of the filepath option on his end. Should we keep this issue open?
