### ISSUE TITLE
dataset tokenization script

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#49]
First, upload just the tokenizer to delphi-suite/tokenizer. Something like this can work
```
from transformers import AutoTokenizer
AutoTokenizer.from_pretrained("v0-llama2-...").push_to_hub("tokenizer")
```
if it doesn't, check [this](https://stackoverflow.com/questions/77265638/how-can-i-push-a-custom-tokenizer-to-huggingface-hub) out. No need to push any code to the repo for this.

Then make a script to tokenize text dataset and upload it to HF
1. pull https://huggingface.co/datasets/delphi-suite/tinystories-v2-clean (dataset name can be an argument with a default, but assume the same format)
2. tokenize each prompt, separate by EOS token and concatenate, divide into 512 length (argument) chunks and prepend BOS to each chunk - this should be doing the same things [this script](https://github.com/delphi-suite/delphi/blob/38b04996edd9febbfba189d03c22bb92c6095fcc/scripts/upload_tokens.py) is doing, but simpler and using HF tokenizer class (PretokDataset is defined in src/llama2c/tinystories.py)

**Comment by siwei-li** [comment]
Todo:

- [x] prompt order in text dataset (not tokenized dataset) randomized already? check w/ Jannick

- [x] deque, add the last one of 512 tokens: https://jamboard.google.com/d/1qsFMR4KexezPVPsfKtuiyVyi0jHbRT4Ga_1O4T1Ny1k/viewer?pli=1&f=1

**Comment by jettjaniak** [comment]
I suggest you have separate functions for
 - extending the deque
   - takes
     - deque of tokens
     - prompt as a list of tokens
       - without special tokens
     - index of EOS a.k.a. `</s>` token
   - returns nothing
   - appends to the deque
 - making a new sample
   - takes
     - deque of tokens
     - last token from previous sample
       - optional, can be None
   - returns a list of 513 tokens 

But instead of implementing them right away, start from writing simple unit tests and ping me and Jai on discord when the tests are done. The 512 should be a variable of course, and in tests we should use 10 or sth
