### ISSUE TITLE
get new non-spacy token labels

### ISSUE THREAD

**Issue by transcendingvictor** [delphi-suite/delphi#53]
My plan is to use the token_labelling.py module, redo the basic categories.
Also, be able to make build categories by interacting manually with on Sheets and exporting the .csv file.

**Comment by jettjaniak** [comment]
*non-spacy

Could you be more specific? What are the TODOs, what's your next step? What
do you mean by using the module? Keep in mind there is a PR open for spacy
token labeling, but should be merged soon

**Comment by jettjaniak** [comment]
ACTUALLY - instead of "is in the dataset" column, let's have "how many times appeared in the dataset column". Then we can sort by this and only focus on first 500-1000 tokens for manual labeling

**Comment by transcendingvictor** [comment]
TO-DOs.
1) Implement the new token categories:
+  is a word
+  instances on dataset

2) Implement a way to retrieve the labels from a .csv file so that we can manually edit categories.

**Comment by jettjaniak** [comment]
also
- starts with space
- capitalized

**Comment by jettjaniak** [comment]
but first we need to merge #40 - can you work on that?
