### ISSUE TITLE
Bug in "delphi-suite/stories-tokenizer"

### ISSUE THREAD

**Issue by menamerai** [delphi-suite/delphi#61]
If we import the tokenizer from HF, it sometimes assume a whitespace is in front of tokens when you encode.

For example, let's say " " is 2222, " cut" is 1221, and "cut" is 3221 (bos is 1). 

When if we call `tokenizer.encode("cut")`, we'll get `[1, 1221]` instead of the expected `[1, 3221]`.
If we call `tokenizer.encode(" cut")`, we'll get `[1, 2222, 1221]` instead of `[1, 2222, 3221]`, or `[1, 1221]`.
If we call `tokenizer.encode("cutcut")`, we'll get `[1, 1221, 3221]`

This suggests that there is bug where the tokenizer assumes spaces in front of words that commonly appears with spaces in front of them. Contact @transcendingvictor for for information.

**Comment by jettjaniak** [comment]
changed tokenizer to byte level BPE
