### ISSUE TITLE
support arbitrary tokenized dataset

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#86]
are we hard-coding our tiny stories tokenized dataset atm?

**Comment by jaidhyani** [comment]
Yup, currently hardcoded,, and we should parameterize it. I think it probably makes sense to let the user specify a hugging face dataset + feature name, provided that that feature is a list of token ints of length max_seq_len+1?

**Comment by jettjaniak** [comment]
sounds good, but default to "tokens" feature name

**Comment by jettjaniak** [comment]
@joshuawe FYI

**Comment by jaidhyani** [comment]
In the current proposed implementation I'm allowing the user to set the train and validation datasets entirely independently if they want. Train and validation are both specified by (dataset, split, feature). Split uses the expected defaults ('train'/'validation'), and feature defaults to 'tokens'. Validation will use train dataset and feature if not specified.

`train dataset`: defaults to `"delphi-suite/v0-tinystories-v2-clean-tokenized"`
`train_split`: defaults to `"train"`
`train_feature`: defaults to `"tokens"`

`validation_dataset`: optional, fallsback to `train_dataset`
`validation_split`: defaults to `"validation"`
`validation_feature`: optional, fallsback to `train_feature`
